$VirtualSwitchName = "Default Switch"

LINUX_IMAGE = "bento/ubuntu-18.04"

Vagrant.configure("2") do |config|
    config.vm.provider "hyperv" do |h|
        h.enable_virtualization_extensions = true
        h.linked_clone = true
        h.cpus = 4
        h.memory = 6144
        h.maxmemory = 8192
        h.vmname = "kind-dev"
    end

    config.vm.define "k8s-dev" do |subconfig|
        subconfig.vm.box = LINUX_IMAGE
        subconfig.vm.hostname = "kind-dev"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName
        config.vm.synced_folder ".", "/vagrant", disabled: true
        subconfig.vm.provision "shell", path: "install.sh"
        subconfig.vm.provision "shell", path: "gitk8s.sh"
    end
end